import * as stylex from "@stylexjs/stylex";

/** Figma: Eki-awase / Metrics. */
export const space = stylex.defineVars({
  "--space-0": "0px",
  "--space-1": "2px",
  "--space-2": "4px",
  "--space-3": "6px",
  "--space-4": "8px",
  "--space-5": "12px",
  "--space-6": "16px",
  "--space-7": "20px",
  "--space-8": "24px",
  "--space-9": "32px",
  "--space-10": "40px",
  "--space-11": "48px",
  "--space-12": "64px",
  "--layout-page-gutter": "16px",
  "--space-repeated-row-block": "12px",
  "--space-repeated-row-gap": "8px",
  "--space-control-gap": "8px",
  "--space-group-gap": "24px",
  "--radius-none": "0px",
  "--radius-sm": "4px",
  "--radius-md": "8px",
  "--radius-lg": "12px",
  "--radius-full": "999px",
  "--icon-size-sm": "20px",
  "--icon-size-md": "24px",
  "--control-height-md": "44px",
  "--control-height-lg": "52px",
  "--hit-area-touch-min": "44px",
  "--row-min-block-size": "48px",
  "--border-width": "1px",
  "--border-width-strong": "2px",
  "--focus-width": "3px",
  "--map-line-context": "2px",
  "--map-line-muted": "4px",
  "--map-line-selected": "6px",
  "--map-marker-stroke": "4px",
  "--map-marker-stroke-selected": "6px",
  "--map-line-dash-on": "8px",
  "--map-line-dash-off": "6px",
});
